merge gm pvc on master
neuropoly/surface_based_tools pull request #4
Opened 2018-01-30 17:34 UTC by gmangeat

- The partial_volume_correction code has beed added to the surfaced_based_tools
- Licences files of external matlab functions have been checked and added where needed

2018-01-31 00:32 UTC, jcohenadad requested changes
image files under /doc: never use space in file names. Also, change file name for something more intuitive. E.g.L figure_outputs.png

2018-01-31 01:36 UTC, jcohenadad submitted a review, later dismissed
Figure_1_intput_example.png
1) typo intput --> input
2) do not add Figure_1 as prefix. If we decide to add figs in the future, it will make the numbering confusing
3) you forgot to update the README with link to figs

2018-01-31 01:36 UTC, jcohenadad commented on partial_volume_correction/PVC/Mesh_voxelisation/COMPUTE_mesh_normals.m
> +% AUTHOR        Adam H. Aitkenhead
what about the license?

2018-01-31 01:36 UTC, jcohenadad commented on partial_volume_correction/PVC/Mesh_voxelisation/CONVERT_meshformat.m
> +% AUTHOR        Adam H. Aitkenhead
license not mentioned

2018-01-31 01:36 UTC, jcohenadad commented on partial_volume_correction/PVC/Mesh_voxelisation/License.txt
> +* Redistributions of source code must retain the above copyright
condition is currently not met-- you need to redirect to the license for each function within the code itself

2018-01-31 01:36 UTC, jcohenadad commented on partial_volume_correction/PVC/Mesh_voxelisation/README.txt
> +adam.aitkenhead@christie.nhs.uk
license

2018-01-31 01:36 UTC, jcohenadad commented on partial_volume_correction/PVC/Mesh_voxelisation/READ_stl.m
> +% AUTHOR:            Adam H. Aitkenhead
license

2018-01-31 01:36 UTC, jcohenadad commented on partial_volume_correction/PVC/Mesh_voxelisation/VOXELISE_example.m
> +%Plot the original STL mesh:
add header + license

2018-01-31 01:36 UTC, jcohenadad commented on partial_volume_correction/PVC/polygon2voxel.m
> +% Function is written by D.Kroon University of Twente (May 2009)
license

2018-01-31 01:36 UTC, jcohenadad commented on partial_volume_correction/PVC/polygon2voxel_double.m
> +function Volume = polygon2voxel_double(FacesA,FacesB,FacesC,VerticesX,VerticesY,VerticesZ,VolumeSize,Wrap)
header  + license

2018-01-31 01:36 UTC, jcohenadad commented on partial_volume_correction/PVC/pvc_compute_unmixed_values.m
> +% Function is written by Camille Van Assel Univertsit� polytechnique de
link to license

2018-01-31 01:36 UTC, jcohenadad commented on partial_volume_correction/PVC/pvc_compute_volume_fraction.m
> +% Original author: Camille Van Assel
license

2018-01-31 01:36 UTC, jcohenadad commented on partial_volume_correction/PVC/pvc_create_expanded_surfaces.m
> +% Function is written by C.Van Assel Univertit� polytechnique de Montreal
license
also, type (i already mentioned that in the previous PR comments: https://github.com/neuropoly/surface_based_tools/pull/1
at this point i will stop doing my comments because I realize i am doing the exact same thing that i already did there:
https://github.com/neuropoly/surface_based_tools/pull/1
so please:
1) read all my comments there: https://github.com/neuropoly/surface_based_tools/pull/1
2) address them
3) ask me for reviewing everything again

2018-01-31 14:33 UTC, gmangeat commented on partial_volume_correction/PVC/Mesh_voxelisation/COMPUTE_mesh_normals.m
> +% AUTHOR        Adam H. Aitkenhead
added in the header

2018-01-31 14:33 UTC, gmangeat commented on partial_volume_correction/PVC/Mesh_voxelisation/CONVERT_meshformat.m
> +% AUTHOR        Adam H. Aitkenhead
added in the header

2018-01-31 14:33 UTC, gmangeat commented on partial_volume_correction/PVC/Mesh_voxelisation/License.txt
> +* Redistributions of source code must retain the above copyright
added in the header

2018-01-31 14:34 UTC, gmangeat commented on partial_volume_correction/PVC/Mesh_voxelisation/README.txt
> +adam.aitkenhead@christie.nhs.uk
added in the header

2018-01-31 14:34 UTC, gmangeat commented on partial_volume_correction/PVC/Mesh_voxelisation/READ_stl.m
> +% AUTHOR:            Adam H. Aitkenhead
added in the header

2018-01-31 14:34 UTC, gmangeat commented on partial_volume_correction/PVC/Mesh_voxelisation/VOXELISE_example.m
> +%Plot the original STL mesh:
done

2018-01-31 14:34 UTC, gmangeat commented on partial_volume_correction/PVC/polygon2voxel.m
> +% Function is written by D.Kroon University of Twente (May 2009)
added in the header

2018-01-31 14:34 UTC, gmangeat commented on partial_volume_correction/PVC/polygon2voxel_double.m
> +function Volume = polygon2voxel_double(FacesA,FacesB,FacesC,VerticesX,VerticesY,VerticesZ,VolumeSize,Wrap)
done

2018-02-08 03:56 UTC, jcohenadad commented on partial_volume_correction/PVC/License_polygon2voxel.txt
> +Copyright (c) 2009, Dirk-Jan Kroon
ok, now this is becoming confusing: there is this txt file which is a license file, that sits in a folder with a bych of files from you and from that author. It is not clear which files this license refers to.
what i meant by "add license info to header" was either to copy/paste the license, or to redirect to a license, but not both. 
To make it perfectly clean, i suggest you create a folder called "ext", with external dependencies. Within ext, you create sub-folders with all borrowed code, and inside each subfolder you put a license file.

2018-02-08 03:58 UTC, jcohenadad approved these changes
great job! i let you merge when you want

2018-02-08 13:28 UTC, merged